name: Prettier
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        prettier_options: --write .
        same_commit: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
